// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/awslabs/operatorpkg/status"
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *InSpaceNodeClass) DeepCopyInto(out *InSpaceNodeClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *InSpaceNodeClass) DeepCopy() *InSpaceNodeClass {
	if in == nil {
		return nil
	}
	out := new(InSpaceNodeClass)
	in.DeepCopyInto(out)
	return out
}

func (in *InSpaceNodeClass) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *InSpaceNodeClassList) DeepCopyInto(out *InSpaceNodeClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]InSpaceNodeClass, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *InSpaceNodeClassList) DeepCopy() *InSpaceNodeClassList {
	if in == nil {
		return nil
	}
	out := new(InSpaceNodeClassList)
	in.DeepCopyInto(out)
	return out
}

func (in *InSpaceNodeClassList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *InSpaceNodeClassSpec) DeepCopyInto(out *InSpaceNodeClassSpec) {
	*out = *in
}

func (in *InSpaceNodeClassStatus) DeepCopyInto(out *InSpaceNodeClassStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = append([]status.Condition(nil), in.Conditions...)
	}
}
