version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]
  - package-ecosystem: gomod
    directory: /modules/cloud-provider
    schedule:
      interval: weekly
    groups:
      go-dependencies:
        patterns: ["*"]
  - package-ecosystem: gomod
    directory: /modules/csi-driver
    schedule:
      interval: weekly
    groups:
      go-dependencies:
        patterns: ["*"]
  - package-ecosystem: gomod
    directory: /modules/karpenter-provider
    schedule:
      interval: weekly
    groups:
      go-dependencies:
        patterns: ["*"]
  - package-ecosystem: docker
    directory: /modules/cloud-provider
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /modules/csi-driver
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /modules/karpenter-provider
    schedule:
      interval: weekly
