version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]
  - package-ecosystem: gomod
    directory: /cloud-provider-inspace
    schedule:
      interval: weekly
    groups:
      go-dependencies:
        patterns: ["*"]
  - package-ecosystem: gomod
    directory: /inspace-csi-driver
    schedule:
      interval: weekly
    groups:
      go-dependencies:
        patterns: ["*"]
  - package-ecosystem: gomod
    directory: /karpenter-provider-inspace
    schedule:
      interval: weekly
    groups:
      go-dependencies:
        patterns: ["*"]
  - package-ecosystem: docker
    directory: /cloud-provider-inspace
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /inspace-csi-driver
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /karpenter-provider-inspace
    schedule:
      interval: weekly
