apiVersion: v2
name: inspace-cloud-kube-modules-crds
description: Karpenter v1.14 and InSpace Cloud custom resource definitions
type: application
version: 0.1.0
appVersion: "1.14.0"
kubeVersion: ">=1.30.0-0"
home: https://github.com/thanet-s/inspace-cloud-kube-modules
sources:
  - https://github.com/thanet-s/inspace-cloud-kube-modules
  - https://github.com/kubernetes-sigs/karpenter
maintainers:
  - name: thanet-s
    url: https://github.com/thanet-s
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/crds: |
    - kind: InSpaceCluster
      version: v1alpha1
      name: inspaceclusters.infrastructure.inspace.cloud
    - kind: InSpaceNodeClass
      version: v1alpha1
      name: inspacenodeclasses.karpenter.inspace.cloud
  org.opencontainers.image.licenses: Apache-2.0
  org.opencontainers.image.source: https://github.com/thanet-s/inspace-cloud-kube-modules
