apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: general
spec:
  limits:
    cpu: "64"
    memory: 128Gi
  template:
    spec:
      nodeClassRef:
        group: karpenter.inspace.cloud
        kind: InSpaceNodeClass
        name: ubuntu-workers-intel
      requirements:
        - key: inspace.cloud/instance-family
          operator: In
          values: [general]
        - key: karpenter.sh/capacity-type
          operator: In
          values: [on-demand]
        - key: kubernetes.io/arch
          operator: In
          values: [amd64]
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 5m
    budgets:
      - nodes: "1"
