{{- if and .Values.ccm.enabled .Values.ccm.serviceAccount.create }}
{{- $component := "ccm" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "inspace.serviceAccountName" (dict "root" . "component" $component "serviceAccount" .Values.ccm.serviceAccount) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "inspace.componentLabels" (dict "root" . "component" $component) | nindent 4 }}
  {{- with .Values.ccm.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
