{{- if and .Values.karpenter.enabled .Values.karpenter.serviceAccount.create }}
{{- $component := "karpenter" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "inspace.serviceAccountName" (dict "root" . "component" $component "serviceAccount" .Values.karpenter.serviceAccount) }}
  namespace: {{ include "inspace.karpenterNamespace" . }}
  labels:
    {{- include "inspace.componentLabels" (dict "root" . "component" $component) | nindent 4 }}
  {{- with .Values.karpenter.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
