{{- if and .Values.karpenter.enabled .Values.karpenter.agentTokenSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: inspace-k3s-agent-token
  namespace: {{ include "inspace.karpenterNamespace" . }}
  labels:
    {{- include "inspace.componentLabels" (dict "root" . "component" "karpenter") | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.karpenter.agentTokenSecret.token | quote }}
{{- end }}
